### ISSUE TITLE
Mysql2::Error: FUNCTION databasename_02.mroonga_command does not exist

### ISSUE THREAD

**Issue by federicocandiago** [clear-code/redmine_full_text_search#72]
Good morning, 

on a Windows machine, I just migrated the full Redmine MySQL-InnoDB database on a MySQL-mroonga database in order for the plugin to work. I just installed, rolled back and re-migrated the plugin, but while on the database if I try to use mroonga functions I have no issues:

```
USE databasename_02;
SELECT mroonga_command('status');
```
When I try to use the plugin, it appears that the commands are not recognised, and I get a 500 error:

```
Mysql2::Error: FUNCTION databasename_02.mroonga_command does not exist:         select mroonga_command(
                 'select', [...])
```

I've actally tried to execute the whole error string on a sql script, and it works correctly. How can I make it work on the plugin as well?

My my.ini file:
```

[mysqld]
# set basedir to your installation path
basedir=C:/mariadb-10.3.17-winx64
# set datadir to the location of your data directory
datadir=C:/mariadb-10.3.17-winx64/data

port=3309

default-storage-engine=InnoDB

# Skip reverse DNS lookup of clients
skip-name-resolve
```

and in my databse.yml file:

```
production:
  adapter: mysql2
  database: databasename_02
  port: 3309
  host: localhost
  username: "username"
  password: "password"
  encoding: utf8
```
Thanks in advance.
